algoritmo "calcularSalario"
// Função :
// Autor :
// Data : 22/08/2023
// Seção de Declarações 
var

   horas : real
   salario : real

inicio

      escreval ("Informe quanto você recebe por hora: ")
      leia (horas)
      escreval ()
      
      escreval ("Informe quantas horas você trabalhou: ")
      leia (salario)
      escreval ()
      
      escreval ("Você receberá R$", (horas * salario), " por ter trabalhado", horas, " horas")

fimalgoritmo
